# -*- coding: utf-8 -*-
"""P1HW1_RodriguezAbdiel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYKAYe9m3fo5Zex-XNjYwumgevXftGCH
"""

# Abdiel Rodriguez
 # 2/10/2025
 # P1HW1
 # Demonstrates code that collects information from user, processes information collected and display results to user.

# Setting up the Math for Exponents
base_value = int(input("Enter an integer as the base value"))
exponent = int(input("Enter an integer as the exponent"))

print()
print("-----Calculating Exponents-----")
print()

print("Enter an integer as the base value: ",base_value)
print("Enter an integer as the exponent: ",exponent)

# Doing the Math for Exponents
result = base_value ** exponent

# Displaying the Math with fancy words for Exponents
print()
print(base_value,"raised to the power of",exponent,"is",result,"!!")

# Start of the Addition and Subtraction part of the problem

print()
print("-----Addition and Subtraction-----")
print()

# Setting up the Math for Addition and subtraction

starting_int = int(input("Enter a starting integer:"))
add_int = int(input("Enter an integer to add: "))
sub_int = int(input("Enter an integer to subtract: "))

# Doing the Math for Addition and subtraction
add_Sub_result = starting_int + add_int - sub_int

# Displaying the Math with fancy words for Addition and subtraction
print()
print(starting_int,"+",add_int,"-",sub_int,"is equal to",add_Sub_result)

