# -*- coding: utf-8 -*-
"""P2LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPr5pKr4XTOh5OLBUTT_E6q5p7RWe0ra
"""

# Abdiel Rodriguez
# 2/12/2025
# P2LAB1
# Code that performs mathematical calculations and displays information to users

# FORMULAS
#-----------------------------------
# Diameter = 2*r
# Circumference = 2*π*r 
# Area = π * r **2
#-----------------------------------


# User Input for Radius

radius = float(input("What is the radius of the circle? "))
print()

# Calculate Diameter using the User Input for radius

diameter = radius * 2
print("The diameter of the circle is", diameter)
print()

# Calculate Circumference using the User Input for radius
pi = 3.14159265359
circumference = 2 * pi * radius

print(f"The circumference of the circle is {circumference:.2f}")
print()

# Calculate Area using the User Input for radius

area = pi * radius ** 2
print(f"The area of the circle is {area:.3f}")

